In [69]:
import pandas as pd
import numpy as np
import plotly.express as px


import plotly.graph_objects as go

# 여러개 그릴 수 있는 plot을 만들어주는거임!
from plotly.subplots import make_subplots




df = pd.read_csv('../data/data1.csv', encoding='cp949')

df


# 1. 데이터 선택
# 2. EDA
# 3. 시각화 or KPI 설정
# 4. KPI 지수 계산
# 5. 대시보드 만들기

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.00
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.00
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.00
3,2024,11,4,신항,외항,수입,7,신항 U 정박지,일반부두,아국선,공컨,0,57,2,0,59,61.00
4,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,적컨,0,31,100,0,131,231.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,2024,7,3,북항,외항,수입환적,8,자성대 부두,컨테이너부두,외국선,적컨,0,8769,6434,0,15203,21637.00
2405,2024,7,3,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,7719,6438,2,14159,20599.50
2406,2024,7,3,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,7818,7253,0,15071,22324.00
2407,2024,11,4,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,2519,2018,3,4540,6561.75
2408,2024,11,4,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,4651,3613,0,8264,11877.00

In [70]:
df['전체물동량'].isna().sum() # 10피트가 0.5로 잡히기 때문 (ㅇㅅㅇ?)

np.int64(0)

In [71]:
print(df['연도'].unique().tolist())
print(df['월'].unique().tolist())
print(df['분기'].unique().tolist())
print(df['청코드'].unique().tolist())
print(df['내외항구분'].unique().tolist())
print(df['수출입구분명'].unique().tolist())

print(df.columns.to_list)

print(df.info())


# df[df[df['내외항구분']=='내항']==df[df['수출입구분명']=='수출환적']]

[2024]
[3, 4, 11, 8, 10, 2, 6, 7, 5, 12, 9, 1]
[1, 2, 4, 3]
['신항', '북항', '감천']
['외항']
['수입', '수입환적', '수출환적', '수출']
<bound method IndexOpsMixin.tolist of Index(['연도', '월', '분기', '청코드', '내외항구분', '수출입구분명', '시설코드', '시설명', '부두구분명',
       '아외국구분', '적공구분', '컨테이너수(10피트)', '컨테이너수(20피트)', '컨테이너수(40피트)',
       '컨테이너수(기타)', '전체개수', '전체물동량'],
      dtype='str')>
<class 'pandas.DataFrame'>
RangeIndex: 2409 entries, 0 to 2408
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   연도           2409 non-null   int64
 1   월            2409 non-null   int64
 2   분기           2409 non-null   int64
 3   청코드          2409 non-null   str
 4   내외항구분        2409 non-null   str
 5   수출입구분명       2409 non-null   str
 6   시설코드         2409 non-null   int64
 7   시설명          2409 non-null   str
 8   부두구분명        2409 non-null   str
 9   아외국구분        2409 non-null   str
 10  적공구분         2409 non-null   str
 11  컨테이너수(10피트)  2409 non-null   int64
 12  컨테이너수(20피트)  2409 non-null   int64
 13  컨테이너수(40피트)  2409 non-null   int64
 14  컨테이너수(기타)    2409 non-null   int64
 15  전체개수         2409 non-null   int64
 16  전체물동량        2409 non-null   float64
dtypes: float64(1), int64(9), str(7)
memory usage: 320.1 KB
None

In [72]:

for col in ['청코드', '내외항구분', '수출입구분명', '부두구분명','아외국구분', '적공구분'] :
    print(col,":",df[col].unique())
    print()

청코드 : <StringArray>
['신항', '북항', '감천']
Length: 3, dtype: str

내외항구분 : <StringArray>
['외항']
Length: 1, dtype: str

수출입구분명 : <StringArray>
['수입', '수입환적', '수출환적', '수출']
Length: 4, dtype: str

부두구분명 : <StringArray>
['일반부두', '컨테이너부두']
Length: 2, dtype: str

아외국구분 : <StringArray>
['외국선', '아국선']
Length: 2, dtype: str

적공구분 : <StringArray>
['적컨', '공컨']
Length: 2, dtype: str

In [73]:
df.groupby(['청코드','월']).size().unstack(level=0)
# 뭘 볼수있는거라고...? 북항이랑 신항이랑 데이터를 비교해서 다른게 맞는거래 근데 뭔소린지 모르게씀

청코드  감천  북항   신항
월
1     7  87   97
2     9  87  101
3    11  94   98
4     8  77  107
5    13  75  113
6     9  70  110
7    10  79  116
8     8  70  112
9     7  89  114
10    8  84  116
11    9  93  117
12   10  86  108

## 목표
- 환적을 얼마나 많이 하는가 (규모)
- 환적을 얼마나 효율적으로 처리하는가 (효율)
    - 머라고..?
        - 머 대비 환적이 얼마나 많은가??? 맞나..????

- 규모와 효율의 문제는 다르게 접근해야 한다는 것을 깨달음
    - 시각화와 동시에 분석 시우시작

In [74]:
# 환적 비중 계산
df['환적여부'] = df['수출입구분명'].isin(['수입환적','수출환적'])

df
# 현재 환적여부에서 false가 52%로 아닌게 더 많지만, 환적은 매년 달라진다.

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량,환적여부
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.00,False
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.00,False
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.00,True
3,2024,11,4,신항,외항,수입,7,신항 U 정박지,일반부두,아국선,공컨,0,57,2,0,59,61.00,False
4,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,적컨,0,31,100,0,131,231.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,2024,7,3,북항,외항,수입환적,8,자성대 부두,컨테이너부두,외국선,적컨,0,8769,6434,0,15203,21637.00,True
2405,2024,7,3,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,7719,6438,2,14159,20599.50,False
2406,2024,7,3,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,7818,7253,0,15071,22324.00,False
2407,2024,11,4,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,2519,2018,3,4540,6561.75,False
2408,2024,11,4,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,4651,3613,0,8264,11877.00,False

In [75]:
zone_total = df.groupby('청코드')['전체물동량'].sum()

zone_total # 청코드별(감천,북항,신항) 전체 컨테이너 처리량

청코드
감천        9014.0
북항     6512510.0
신항    17880496.0
Name: 전체물동량, dtype: float64

In [76]:
zone_transship = df[df['환적여부']].groupby('청코드')['전체물동량'].sum()
zone_transship

청코드
감천        6192.00
북항     2314512.75
신항    11176479.25
Name: 전체물동량, dtype: float64

In [77]:
zone_share = ((zone_transship/zone_total)*100).round(2)

zone_share # 구성이 아니라 성과를 볼 수 있는 것!
# 이를 통해 안 사실
# "북항도 환적이 많을 줄 알았는데 아니였다"
# "감천은 벌크가 많이 들어오는 항구였다"

# 환적에 대한 지표를 뭘 볼건지
# 항만크레인이 컨테이너를 한번 들어옮기는 작업을 할때 몇피트건 같은 횟수로
#컨테이너 1개당 평균 몇 teu를 실어나르는가? (???????????)
# teu_factor라는 실제 용어

청코드
감천    68.69
북항    35.54
신항    62.51
Name: 전체물동량, dtype: float64

In [78]:
# 데이터의 신뢰도를 확인해봐야 함. (수기데이터일 경우 휴먼에러 가능성)

df.columns

df[df['환적여부']].groupby('청코드')['컨테이너수(기타)'].sum()

청코드
감천        0
북항       51
신항    32877
Name: 컨테이너수(기타), dtype: int64

In [79]:
teu_estimate = df['컨테이너수(10피트)']*0.5+df['컨테이너수(20피트)']*1+df['컨테이너수(40피트)']*2

# corr 다시 공부하기
# 높은 상관계수를 가지고 있기 때문에 전체물동량을 사용해도 되겠다는 판단을 해도 됨.
teu_estimate.corr(df['전체물동량'])

np.float64(0.9999898787140992)

In [80]:
# agg 뭔지 공부하기
# 각 항별 몇개를 처리했고, 물동량이 얼마나 처리됐는지 확인 40pt 짜리를 많이 깐게 더 효율이 좋은것!
grp = df.groupby(['청코드','환적여부']).agg(물동량=('전체물동량','sum'),개수=('전체개수','sum'))

grp['TEU_FACTOR'] = (grp['물동량']/grp['개수']).round(2)

# 2에 가까우면 40피트짜리를 많이 깐거라고 볼수있음!
# 북항과 비교했을 때 신항은 대형화물을 처리할 가능성이 높음
grp

# 전체 컨테이너 대비 공컨이 얼마나 차지하는지
grp2 = df.groupby(['청코드','환적여부','적공구분'])['전체물동량'].sum().unstack(fill_value=0)

In [81]:
grp2['공컨비율(%)'] = ((grp2['공컨']/ (grp2['공컨']+ grp2['적컨']))*100).round(2)

grp2

#?? 신항이니까 공컨 비율이 낮아야한다는 생각이 왜 드는거지?????
# 공컨비율이 더 높을 줄 알았더니 아니였다!?!?

# 환적비중으로는 효율문제를 확인 할 수 없다.는걸 깨달음(?)

# 메인항구가 신항이니까

# 환적에서 보고싶었던게 뭐였냐면

적공구분              공컨           적컨  공컨비율(%)
청코드 환적여부
감천  False     1083.0      1739.00    38.38
    True         0.0      6192.00     0.00
북항  False  1314340.5   2883656.75    31.31
    True     45790.0   2268722.75     1.98
신항  False  1983822.0   4720194.75    29.59
    True    713056.0  10463423.25     6.38

원래목표 (
- 환적을 얼마나 많이 하는가 (규모)
- 환적을 얼마나 효율적으로 처리하는가 (효율)
)

-> 규모와 효율의 문제는 다르게 접근해야 한다는 것을 깨달음
    - 시각화와 동시에 분석 시우시작

In [82]:
# TEU_FACTOR랑 환적공컨비율이랑 뭐해본다고??
grp_plot = grp.reset_index()

# 범례 바꾸기 (.map({a:A, b:B}))
grp_plot['환적여부'] = grp_plot['환적여부'].map({True:'환적', False:'수출입(일반)'})

grp_plot

  청코드     환적여부          물동량       개수  TEU_FACTOR
0  감천  수출입(일반)      2822.00     1516        1.86
1  감천       환적      6192.00     3210        1.93
2  북항  수출입(일반)   4197997.25  2859718        1.47
3  북항       환적   2314512.75  1569611        1.47
4  신항  수출입(일반)   6704016.75  4140278        1.62
5  신항       환적  11176479.25  6464959        1.73

In [83]:
grp_plot = grp_plot[grp_plot['청코드'] != '감천']

grp_plot

  청코드     환적여부          물동량       개수  TEU_FACTOR
2  북항  수출입(일반)   4197997.25  2859718        1.47
3  북항       환적   2314512.75  1569611        1.47
4  신항  수출입(일반)   6704016.75  4140278        1.62
5  신항       환적  11176479.25  6464959        1.73

In [84]:
fig = px.bar(
    grp_plot,
    x='청코드',
    y='TEU_FACTOR',
    color='환적여부',
    barmode='group',
    title='청코드, 환적여부별 컨테이너당 TEU'
)

fig.show()

In [85]:
grp2_plot = grp2.reset_index()
grp2_plot['환적여부'] = grp2_plot['환적여부'].map({True:'환적', False:'수출입(일반)'})
grp2_plot = grp2_plot[grp2_plot['청코드'] != '감천']

grp2_plot

적공구분 청코드     환적여부         공컨           적컨  공컨비율(%)
2     북항  수출입(일반)  1314340.5   2883656.75    31.31
3     북항       환적    45790.0   2268722.75     1.98
4     신항  수출입(일반)  1983822.0   4720194.75    29.59
5     신항       환적   713056.0  10463423.25     6.38

In [86]:
fig = px.bar(
    grp2_plot,
    x='청코드',
    y='공컨비율(%)',
    color='환적여부',
    barmode='group',
    title='청코드, 환적여부별 공컨비율',
)

# 북항이 우위를 갖고있구나??
fig.show()

#효율성이 흔들리냐 흔들리지않느냐 ? 여유있는 능력을 갖췄다
#물동량이 늘어날때 효율지표가 떨어지면 병목현상이 있다고 판단할 수 있다.
#월별 물동량을 놓고 판단해야한다????

물동량이 몰리는 달에도 우리가 구한 factor와 같은 처리효율지표가 안정적으로 유지된다면, 해당항만은 물동량 변화에 잘 대응하는 여유있는 운영능력을 갖추었다고 판단할 수 있는 것이고, 반대로 물동량이 늘었을때 효율이 떨어진다면 처리능력에 병목이 있다고 볼 수 있는 것이다.

In [93]:
sinhang = df[df['청코드'] == '신항']

monthly_sinhang = sinhang.groupby('월').agg(물동량=('전체물동량','sum'),개수=('전체개수','sum'))

# agg 한게 지금은 잘 보이는데 뭔가 이상하게 나온다고 함 그래서 리셋 하는거임
monthly_sinhang = monthly_sinhang.reset_index()

#
monthly_sinhang['TEU_FACTOR'] = monthly_sinhang['물동량']/monthly_sinhang['개수']

In [95]:
#여러 그래프 그리기

# specs=[{'secondary_y':True}]~~ : Y축을 두개 걸수있음!!
fig_dual = make_subplots(specs=[[{'secondary_y':True}]])

# fig랑 x 받는 게 복잡하다.

# 각각의 객체설정을 해주는거
fig_dual.add_trace(
    go.Bar(
        x=monthly_sinhang['월'],
        y=monthly_sinhang['물동량'],
        name='물동량(TEU)'
    ),
    secondary_y=False,
)


fig_dual.add_trace(
    go.Scatter(
        x=monthly_sinhang['월'],
        y=monthly_sinhang['TEU_FACTOR'],
        mode='lines+markers',
    ),
    secondary_y=True,
)

fig_dual.update_yaxes(secondary_y=True, range=[1.5, 1.8,])

fig_dual.show()

# 지표가 왜곡되지는 않았구나
# 물동량이 많이 오른다고 해도 teu비율이 일정하게 유지되고 있다.
# 규모에 대해서는 안정정적인 비율로 유지되고 있다.

# 여기서 회귀선을 보자.
# 물동량이 늘어날때 teu가 늘어날지 그런 방향을 볼것

# 여기까지만 해도 KPI를 설정할 수 있다.

In [99]:
# 회귀선.

# 예측모델을 만들기 위해서는 만들수있어야한다!

# 기울기와 절편을 구할때 사용
import numpy as np

# 가중치,slope,기울기(w) 편향,intercept,절편(b)
# y = wx + b
# 독립변수x와 종속변수y를 넣는다.
slope, intercept = np.polyfit(
    monthly_sinhang['물동량'],
    monthly_sinhang['TEU_FACTOR'],
    1
)
fig_scatter = go.Figure()

fig_scatter.add_trace(
    go.Scatter(
        x=monthly_sinhang['물동량'],
        y=monthly_sinhang['TEU_FACTOR'],
        mode='markers+text',
        text=monthly_sinhang['월'],
        name='월별 관측치'
    )
)

x_range=[monthly_sinhang['물동량'].min(),monthly_sinhang['물동량'].max(),]


fig_scatter.add_trace(
    go.Scatter(
        x=x_range,
        y=[ slope * x + intercept for x in x_range  ],
        mode='lines',
        name='회귀선'
    )
)

fig_scatter.show() # 현재 많이 떨어져있기 때문에 가중치를 좀 더 줘야된다.

In [ ]:
# 여태까지 분석한 내용을 가지고 KPI를 설정할것!
# 예측모델 만드는게 들어간다
# 분석이 완료되면 미래예측이 들어감.
# 회귀모델 중에서도 1차함수를 사용하여 들어감.